server:
  ssl:
    key-store: classpath:https_keystore.p12
    key-store-password: chujian
    keyStoreType: PKCS12
    keyAlias: 1
  port: 8443
  http-port: 8080
  servlet:
    application-display-name: firstmeet-mservice-paycenter-chujian-zfb
    contextPath: /
  tomcat:
    basedir: "./"
    accesslog:
      enabled: true
      directory: ${FIRSTMEET_MSERVICE_DATA_BASEDIR:.}/logs/${HOSTNAME:1}/access-log
    customized.enable: true
    customized.accept-count: 100
    customized.max-threads: 200
    customized.min-spare-threads: 25
    customized.max-connections: 10000
    customized.connection-timeout: 2000
    manager.enable: false
    manager.context-path: '/data/webapps/manager'

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://192.168.1.220:3306/pay_center_chujian_zfb?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: kaifa
    password: chujian8
    druid:
      initial-size: 50
      min-idle: 50
      max-active: 600
      max-wait: 2000  #配置获取连接等待超时的时间
      time-between-eviction-runs-millis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000 #配置一个连接在池中最小生存的时间，单位是毫秒
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filters: stat,slf4j
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  jackson:
    serialization:
      indent_output: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

paycenter.chujian.host.url: 'https://upsdev.16801.com/chujianpay'

alipay:
  payment:
    url: 'https://openapi.alipay.com/gateway.do'
    notify.url: '${paycenter.chujian.host.url}/chujianpay/zfb/callback'
    return.url: 'TestSDK://TestSDK.13cd.com'

chujian:
   token:
     key:
       public-key-string: 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlTulF2dCQQiU4jkQMQHth084/OZcLFGkse6BQ0J5u47TOJ7PGPMAX1iqCrCwgbseDNLjMMpxLuX4ULbpjFrD/FN1uKmXEVwdP9zYCv22hE618XU6j3u0OEfsgZrupv9+lALxGZKyDfDRsjEy5KCXekAOiXDxJEUl/pNYla8MoJ5D9zjjUzUVq8i3pdL42sP9z6LKhtQXtzOiQ22zGST3mMzButpYXK55LHlgqYXb9hjBbcVIsZYP07Q4mt+NlT+x4crYp4Hirjl9rbUmQm7ZoL3GR8ErJnipPqOo7uKCAmwjKnBoRSu5836gG6kLOiSHtCdu8hp96G8sS95oWorflwIDAQAB'
   drools:
     rule:
       path: 'classpath*:rules/**/client-config-dev.xls' #Can configure absolute path: file:/data/rules/**/*.drl

uid.grpc:
  host: 'uidgenerator.ups.firstmeet'
  port: 6565


